//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Programı {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stok_Programı.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adet:.
        /// </summary>
        internal static string adet {
            get {
                return ResourceManager.GetString("adet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        internal static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYARLAR.
        /// </summary>
        internal static string ayarlar {
            get {
                return ResourceManager.GetString("ayarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi Fişi.
        /// </summary>
        internal static string bilgifisi {
            get {
                return ResourceManager.GetString("bilgifisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Tarihi:.
        /// </summary>
        internal static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Tercihi.
        /// </summary>
        internal static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Dokümanı.
        /// </summary>
        internal static string excel_dokumani {
            get {
                return ResourceManager.GetString("excel_dokumani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULLANICI GİRİŞİ.
        /// </summary>
        internal static string form1 {
            get {
                return ResourceManager.GetString("form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜN KAYIT FORMU.
        /// </summary>
        internal static string form3 {
            get {
                return ResourceManager.GetString("form3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FİRMA KAYIT FORMU.
        /// </summary>
        internal static string form4 {
            get {
                return ResourceManager.GetString("form4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜN ÇIKIŞ.
        /// </summary>
        internal static string form5 {
            get {
                return ResourceManager.GetString("form5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANA İŞLEM PANELİ.
        /// </summary>
        internal static string form6 {
            get {
                return ResourceManager.GetString("form6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜN GİRİŞ.
        /// </summary>
        internal static string form7 {
            get {
                return ResourceManager.GetString("form7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARAÇLAR.
        /// </summary>
        internal static string form8 {
            get {
                return ResourceManager.GetString("form8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Tarihi:.
        /// </summary>
        internal static string giris {
            get {
                return ResourceManager.GetString("giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl:.
        /// </summary>
        internal static string il {
            get {
                return ResourceManager.GetString("il", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe:.
        /// </summary>
        internal static string ilce {
            get {
                return ResourceManager.GetString("ilce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        internal static string ingilizce {
            get {
                return ResourceManager.GetString("ingilizce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem:.
        /// </summary>
        internal static string islem {
            get {
                return ResourceManager.GetString("islem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string lbl_anasayfa {
            get {
                return ResourceManager.GetString("lbl_anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string lbl_cikis {
            get {
                return ResourceManager.GetString("lbl_cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Hattı: 0 (236) 231 40 10.
        /// </summary>
        internal static string lbl_destek {
            get {
                return ResourceManager.GetString("lbl_destek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adı:.
        /// </summary>
        internal static string lbl_firmaadi {
            get {
                return ResourceManager.GetString("lbl_firmaadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Tarihi:.
        /// </summary>
        internal static string lbl_kayit {
            get {
                return ResourceManager.GetString("lbl_kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        internal static string lbl_kullanici_adi {
            get {
                return ResourceManager.GetString("lbl_kullanici_adi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULLANICI GİRİŞİ.
        /// </summary>
        internal static string lbl_kullanicigiris {
            get {
                return ResourceManager.GetString("lbl_kullanicigiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        internal static string lbl_sifre {
            get {
                return ResourceManager.GetString("lbl_sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kodu:.
        /// </summary>
        internal static string lbl_urunkodu {
            get {
                return ResourceManager.GetString("lbl_urunkodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yardım.
        /// </summary>
        internal static string lbl_yardim {
            get {
                return ResourceManager.GetString("lbl_yardim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mersis No:.
        /// </summary>
        internal static string mersis {
            get {
                return ResourceManager.GetString("mersis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu:.
        /// </summary>
        internal static string sorumlu {
            get {
                return ResourceManager.GetString("sorumlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numarası:.
        /// </summary>
        internal static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string türkçe {
            get {
                return ResourceManager.GetString("türkçe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Dairesi:.
        /// </summary>
        internal static string vergi {
            get {
                return ResourceManager.GetString("vergi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi No:.
        /// </summary>
        internal static string vergi_no {
            get {
                return ResourceManager.GetString("vergi_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazıcı Ekle.
        /// </summary>
        internal static string y_ekle {
            get {
                return ResourceManager.GetString("y_ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazıcılar:.
        /// </summary>
        internal static string yazici {
            get {
                return ResourceManager.GetString("yazici", resourceCulture);
            }
        }
    }
}
